name: Release Catalog

on:
  workflow_dispatch:
    inputs:
      specific_release_version:
        description: Define the specific release version?
        required: false
      release_version:
        type: choice
        description: What kind of release do you want to do?
        required: false
        options:
        - patch
        - minor
        - major
      
jobs:
  clean_build:
    runs-on: ubuntu-latest
    environment:
      name: release_environment
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Setup android sdk
        if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        uses: android-actions/setup-android@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module
        run: ./gradlew clean build
  update_catalog_version:
    runs-on: ubuntu-latest
    needs: clean_build
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependecy
        run: python3 -m pip install semver
      - name: Update catalog version
        if: "${{ github.event.inputs.release_version != '' }}"
        run: ./gradlew updateCatalog -PnewCatalogVersion=${{ github.event.inputs.release_version }}
      - name: Update catalog version
        if: "${{ github.event.inputs.specific_release_version != '' }}"
        run: ./gradlew updateCatalog -PnewCatalogVersion=${{github.event.inputs.specific_release_version }}
  release_catalog_version:
    runs-on: ubuntu-latest
    needs: update_catalog_version
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Release new catalog version
        run: ./gradlew publishUploadCatalog -PdryRun=false