name: Release Bom

on:
  workflow_dispatch:
    inputs:
      specific_release_version:
        description: Define the specific release version?
        required: false
      release_version:
        type: choice
        description: What kind of release do you want to do?
        required: false
        options:
        - patch
        - minor
        - major
    secrets:
      MAVEN_ACCESSKEY:
        required: true
      MAVEN_SECRETKEY:
        required: true
      MAVEN_DISTRIBUTIONID:
        required: true
      
jobs:
  clean_build:
    runs-on: ubuntu-latest
    environment:
      name: release_environment
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Setup android sdk
        if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        uses: android-actions/setup-android@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module
        run: ./gradlew clean build
  update_bom_version:
    runs-on: ubuntu-latest
    needs: clean_build
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: add python dependency
        run:  python3 -m pip install semver boto3
      - name: Update bom semver version
        id: output_semver_tag
        if: "${{ github.event.inputs.release_version != '' }}"
        run: ./gradlew updateBom -PnewBomVersion=${{ github.event.inputs.release_version }}
      - name: Update bom specific version
        id: output_specific_tag
        if: "${{ github.event.inputs.specific_release_version != '' }}"
        run: ./gradlew updateBom -PnewBomVersion=${{github.event.inputs.specific_release_version }}
      - name: Update Maven credentials
        env:
          MAVEN_ACCESSKEY: ${{ secrets.MAVEN_ACCESSKEY }}
          MAVEN_SECRETKEY: ${{ secrets.MAVEN_SECRETKEY }}
          MAVEN_DISTRIBUTIONID: ${{ secrets.MAVEN_DISTRIBUTIONID }}
        run:
          echo -e "maven.accessKey=$MAVEN_ACCESSKEY\nmaven.secretKey=$MAVEN_SECRETKEY\nmaven.distributionId=$MAVEN_DISTRIBUTIONID" >> ./local.properties
      - name: Release new bom version
        run: ./gradlew publishUploadBom -PdryRun=false
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update bom version
          tagging_message: ${{ steps.output_specific_tag.outputs.TAG || steps.output_semver_tag.outputs.TAG }}