name: Release Bom

on:
  workflow_call:
    inputs:
        specific_release_version:
          description: Define the specific release version?
          required: false
          type: string
        release_version:
          type: string
          description: What kind of release do you want to do?
          required: false
  
  workflow_dispatch:
    inputs:
      specific_release_version:
        description: Define the specific release version?
        required: false
      release_version:
        type: choice
        description: What kind of release do you want to do?
        required: false
        options:
        - patch
        - minor
        - major
jobs:
  clean_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./androidDependenciesCatalog
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with: 
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: AndroidDependenciesCatalog
      - uses: actions/checkout@v2
        with: 
          repository: KaleyraVideo/AndroidDependenciesCatalog
          path: androidDependenciesCatalog
          ref: 'main'
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup android sdk
        uses: android-actions/setup-android@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module
        run: ./gradlew clean build
  update_bom_version:
    runs-on: ubuntu-latest
    needs: clean_build
    defaults:
      run:
        working-directory: ./androidDependenciesCatalog
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with: 
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: AndroidDependenciesCatalog
      - uses: actions/checkout@v2
        with:
          repository: KaleyraVideo/AndroidDependenciesCatalog
          path: androidDependenciesCatalog
          ref: 'main'
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: add python dependency
        run:  python3 -m pip install semver boto3
      - name: Update bom  version
        id: output_tag
        run: ./gradlew updateBom -PnewBomVersion=${{github.event.inputs.specific_release_version || github.event.inputs.release_version }}
      - name: Update Maven credentials
        env:
          MAVEN_ACCESSKEY: ${{ secrets.MAVEN_ACCESSKEY }}
          MAVEN_SECRETKEY: ${{ secrets.MAVEN_SECRETKEY }}
          MAVEN_DISTRIBUTIONID: ${{ secrets.MAVEN_DISTRIBUTIONID }}
        run:
          echo -e "maven.accessKey=$MAVEN_ACCESSKEY\nmaven.secretKey=$MAVEN_SECRETKEY\nmaven.distributionId=$MAVEN_DISTRIBUTIONID" >> ./local.properties
      - name: Release new bom version
        run: ./gradlew publishUploadBom -PdryRun=false
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./androidDependenciesCatalog
          commit_message: Update bom version
          tagging_message: ${{ steps.output_tag.outputs.TAG }}
