name: Update dependency library

on:
  workflow_call:
    inputs:
      library_name:
        type: string
        description: Define the kaleyra library name that needs to be updated
        required: true
      library_version:
        type: string
        description: Define the kaleyra library version that needs to be updated
        required: true
        
  workflow_dispatch:
    inputs:
      library_name:
        description: Select the kaleyra library variable name that needs to be updated
        type: choice
        options:
        - 
        - kaleyraVideoCoreAvVersion
        - bandyerFirecrasherVersion
        - kaleyraCommunicationCenterVersion
        - kaleyraAudioSessionVersion
        - kaleyraChatSdkVersion
        - kaleyraVideoVersion
        - kaleyraVideoUtilsVersion
        - kaleyraVideoNetworkingVersion
        - kaleyraSocketIoVersion
        required: true
      library_version:
        description: Define the kaleyra library version that needs to be updated
        required: true

jobs:
  determine-runner-integration:
    name: Determine which runner to use for integration tests
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Determine which runner to use
        id: set-runner
        uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
        with:
          primary-runner: "self-hosted"
          fallback-runner: "ubuntu-latest"
          min-available-runners: 1
          github-token: ${{steps.generate_token.outputs.token}}
  clean_build:
    needs: determine-runner-integration
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Setup android sdk
        uses: android-actions/setup-android@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build module
        run: ./gradlew clean build
  update_library:
    needs: [ determine-runner-integration, clean_build ]
    runs-on: ${{ needs.determine-runner-integration.outputs.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Setup android sdk
        uses: android-actions/setup-android@v3
      - name: Update kaleyra dependency library version
        run: ./gradlew updateKaleyraLibVersion -PkaleyraLibName=${{ inputs.library_name }} -PkaleyraLibVersion=${{ inputs.library_version }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update library ${{ inputs.library_name }} to ${{ inputs.library_version }}
