name: Update kaleyra dependency and release Catalog

on:
  workflow_call:
    inputs:
      specific_catalog_release_version:
        description: Define the specific release version?
        type: string
        required: false
      library_name:
        type: string
        description: Define the kaleyra library name that needs to be updated
        required: true
      library_version:
        type: string
        description: Define the kaleyra library version that needs to be updated
        required: true
    secrets:
      MAVEN_ACCESSKEY:
        required: true
      MAVEN_SECRETKEY:
        required: true
      MAVEN_DISTRIBUTIONID:
        required: true
        
  workflow_dispatch:
    inputs:
      specific_catalog_release_version:
        description: Define the specific release version?
        required: false
      library_name:
        description: Select the kaleyra library variable name that needs to be updated
        type: choice
        options:
        - 
        - kaleyraVideoCoreAvVersion
        - bandyerFirecrasherVersion
        - kaleyraCommunicationCenterVersion
        - kaleyraAudioSessionVersion
        - kaleyraChatSdkVersion
        - kaleyraVideoVersion
        - kaleyraVideoUtilsVersion
        - kaleyraVideoNetworkingVersion
        - kaleyraSocketIoVersion
        required: true
      library_version:
        description: Define the kaleyra library version that needs to be updated
        required: true
    secrets:
      MAVEN_ACCESSKEY:
        required: true
      MAVEN_SECRETKEY:
        required: true
      MAVEN_DISTRIBUTIONID:
        required: true
jobs:
  update_library:
    uses: KaleyraVideo/AndroidDependenciesCatalog/.github/workflows/update_dependency_library.yml@main
    with:
      library_name: ${{ github.event.inputs.library_name }}
      library_version: ${{ github.event.inputs.library_version }}
    secrets: inherit
  release_catalog:
    needs: update_library
    uses: KaleyraVideo/AndroidDependenciesCatalog/.github/workflows/release_catalog.yml@main
    with:
        specific_release_version: ${{ github.event.inputs.specific_catalog_release_version }}
    secrets: inherit
